---
on:
  release:
    types: [published]

env:
  PIP_SECRET_KEY: ${{ secrets.PIP_SECRET_KEY }}
  
jobs:
  upload-release:
    name: "Publish builder release to pip"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Publish builder into pip repository
        run: |
          # Setup twine
          pip install twine
          
          GITHUB_TOKEN=${{ secrets.TOKEN }}
          GITHUB_API_URL=https://api.github.com/repos/danilapog/DocumentBuilder/releases/latest
          release_info=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -s $GITHUB_API_URL)
          whl_url=($(echo "$release_info" | jq -r '.assets[] | select(.name | test("document_builder-.*\\.whl")) | .browser_download_url'))
          
          if [[ -z "${whl_url[@]}" ]]; then
             echo "Nothing to publish, there is no whl files..."
             exit 0
          else
             mkdir ./dist
          fi
          
          for i in ${whl_url[@]}; do
             wget -P ./dist ${i}
          done

          python3 -m twine upload  dist/* -u __token__ -p ${PIP_SECRET_KEY}
          echo "Finished..."
